/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package iot;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SingleVsDouble extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8677892851113586632L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SingleVsDouble\",\"namespace\":\"iot\",\"fields\":[{\"name\":\"customerId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"dosage\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SingleVsDouble> ENCODER =
      new BinaryMessageEncoder<SingleVsDouble>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SingleVsDouble> DECODER =
      new BinaryMessageDecoder<SingleVsDouble>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<SingleVsDouble> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<SingleVsDouble> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SingleVsDouble>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this SingleVsDouble to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a SingleVsDouble from a ByteBuffer. */
  public static SingleVsDouble fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String customerId;
  @Deprecated public int dosage;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SingleVsDouble() {}

  /**
   * All-args constructor.
   * @param customerId The new value for customerId
   * @param dosage The new value for dosage
   */
  public SingleVsDouble(java.lang.String customerId, java.lang.Integer dosage) {
    this.customerId = customerId;
    this.dosage = dosage;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return customerId;
    case 1: return dosage;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: customerId = (java.lang.String)value$; break;
    case 1: dosage = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'customerId' field.
   * @return The value of the 'customerId' field.
   */
  public java.lang.String getCustomerId() {
    return customerId;
  }

  /**
   * Sets the value of the 'customerId' field.
   * @param value the value to set.
   */
  public void setCustomerId(java.lang.String value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'dosage' field.
   * @return The value of the 'dosage' field.
   */
  public java.lang.Integer getDosage() {
    return dosage;
  }

  /**
   * Sets the value of the 'dosage' field.
   * @param value the value to set.
   */
  public void setDosage(java.lang.Integer value) {
    this.dosage = value;
  }

  /**
   * Creates a new SingleVsDouble RecordBuilder.
   * @return A new SingleVsDouble RecordBuilder
   */
  public static iot.SingleVsDouble.Builder newBuilder() {
    return new iot.SingleVsDouble.Builder();
  }

  /**
   * Creates a new SingleVsDouble RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SingleVsDouble RecordBuilder
   */
  public static iot.SingleVsDouble.Builder newBuilder(iot.SingleVsDouble.Builder other) {
    return new iot.SingleVsDouble.Builder(other);
  }

  /**
   * Creates a new SingleVsDouble RecordBuilder by copying an existing SingleVsDouble instance.
   * @param other The existing instance to copy.
   * @return A new SingleVsDouble RecordBuilder
   */
  public static iot.SingleVsDouble.Builder newBuilder(iot.SingleVsDouble other) {
    return new iot.SingleVsDouble.Builder(other);
  }

  /**
   * RecordBuilder for SingleVsDouble instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SingleVsDouble>
    implements org.apache.avro.data.RecordBuilder<SingleVsDouble> {

    private java.lang.String customerId;
    private int dosage;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(iot.SingleVsDouble.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.customerId)) {
        this.customerId = data().deepCopy(fields()[0].schema(), other.customerId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.dosage)) {
        this.dosage = data().deepCopy(fields()[1].schema(), other.dosage);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing SingleVsDouble instance
     * @param other The existing instance to copy.
     */
    private Builder(iot.SingleVsDouble other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.customerId)) {
        this.customerId = data().deepCopy(fields()[0].schema(), other.customerId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.dosage)) {
        this.dosage = data().deepCopy(fields()[1].schema(), other.dosage);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'customerId' field.
      * @return The value.
      */
    public java.lang.String getCustomerId() {
      return customerId;
    }

    /**
      * Sets the value of the 'customerId' field.
      * @param value The value of 'customerId'.
      * @return This builder.
      */
    public iot.SingleVsDouble.Builder setCustomerId(java.lang.String value) {
      validate(fields()[0], value);
      this.customerId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'customerId' field has been set.
      * @return True if the 'customerId' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'customerId' field.
      * @return This builder.
      */
    public iot.SingleVsDouble.Builder clearCustomerId() {
      customerId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'dosage' field.
      * @return The value.
      */
    public java.lang.Integer getDosage() {
      return dosage;
    }

    /**
      * Sets the value of the 'dosage' field.
      * @param value The value of 'dosage'.
      * @return This builder.
      */
    public iot.SingleVsDouble.Builder setDosage(int value) {
      validate(fields()[1], value);
      this.dosage = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'dosage' field has been set.
      * @return True if the 'dosage' field has been set, false otherwise.
      */
    public boolean hasDosage() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'dosage' field.
      * @return This builder.
      */
    public iot.SingleVsDouble.Builder clearDosage() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SingleVsDouble build() {
      try {
        SingleVsDouble record = new SingleVsDouble();
        record.customerId = fieldSetFlags()[0] ? this.customerId : (java.lang.String) defaultValue(fields()[0]);
        record.dosage = fieldSetFlags()[1] ? this.dosage : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SingleVsDouble>
    WRITER$ = (org.apache.avro.io.DatumWriter<SingleVsDouble>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SingleVsDouble>
    READER$ = (org.apache.avro.io.DatumReader<SingleVsDouble>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
