/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package iot;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UsagePerGroup extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7484317888236520137L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UsagePerGroup\",\"namespace\":\"iot\",\"fields\":[{\"name\":\"CoffeeMachineIdGroupIdKey\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"CoffeeMachineId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"GroupId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"count\",\"type\":\"long\",\"default\":0}],\"connect.name\":\"iot\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UsagePerGroup> ENCODER =
      new BinaryMessageEncoder<UsagePerGroup>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UsagePerGroup> DECODER =
      new BinaryMessageDecoder<UsagePerGroup>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<UsagePerGroup> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<UsagePerGroup> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UsagePerGroup>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this UsagePerGroup to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a UsagePerGroup from a ByteBuffer. */
  public static UsagePerGroup fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String CoffeeMachineIdGroupIdKey;
  @Deprecated public java.lang.String CoffeeMachineId;
  @Deprecated public java.lang.String GroupId;
  @Deprecated public long count;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UsagePerGroup() {}

  /**
   * All-args constructor.
   * @param CoffeeMachineIdGroupIdKey The new value for CoffeeMachineIdGroupIdKey
   * @param CoffeeMachineId The new value for CoffeeMachineId
   * @param GroupId The new value for GroupId
   * @param count The new value for count
   */
  public UsagePerGroup(java.lang.String CoffeeMachineIdGroupIdKey, java.lang.String CoffeeMachineId, java.lang.String GroupId, java.lang.Long count) {
    this.CoffeeMachineIdGroupIdKey = CoffeeMachineIdGroupIdKey;
    this.CoffeeMachineId = CoffeeMachineId;
    this.GroupId = GroupId;
    this.count = count;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CoffeeMachineIdGroupIdKey;
    case 1: return CoffeeMachineId;
    case 2: return GroupId;
    case 3: return count;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CoffeeMachineIdGroupIdKey = (java.lang.String)value$; break;
    case 1: CoffeeMachineId = (java.lang.String)value$; break;
    case 2: GroupId = (java.lang.String)value$; break;
    case 3: count = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'CoffeeMachineIdGroupIdKey' field.
   * @return The value of the 'CoffeeMachineIdGroupIdKey' field.
   */
  public java.lang.String getCoffeeMachineIdGroupIdKey() {
    return CoffeeMachineIdGroupIdKey;
  }

  /**
   * Sets the value of the 'CoffeeMachineIdGroupIdKey' field.
   * @param value the value to set.
   */
  public void setCoffeeMachineIdGroupIdKey(java.lang.String value) {
    this.CoffeeMachineIdGroupIdKey = value;
  }

  /**
   * Gets the value of the 'CoffeeMachineId' field.
   * @return The value of the 'CoffeeMachineId' field.
   */
  public java.lang.String getCoffeeMachineId() {
    return CoffeeMachineId;
  }

  /**
   * Sets the value of the 'CoffeeMachineId' field.
   * @param value the value to set.
   */
  public void setCoffeeMachineId(java.lang.String value) {
    this.CoffeeMachineId = value;
  }

  /**
   * Gets the value of the 'GroupId' field.
   * @return The value of the 'GroupId' field.
   */
  public java.lang.String getGroupId() {
    return GroupId;
  }

  /**
   * Sets the value of the 'GroupId' field.
   * @param value the value to set.
   */
  public void setGroupId(java.lang.String value) {
    this.GroupId = value;
  }

  /**
   * Gets the value of the 'count' field.
   * @return The value of the 'count' field.
   */
  public java.lang.Long getCount() {
    return count;
  }

  /**
   * Sets the value of the 'count' field.
   * @param value the value to set.
   */
  public void setCount(java.lang.Long value) {
    this.count = value;
  }

  /**
   * Creates a new UsagePerGroup RecordBuilder.
   * @return A new UsagePerGroup RecordBuilder
   */
  public static iot.UsagePerGroup.Builder newBuilder() {
    return new iot.UsagePerGroup.Builder();
  }

  /**
   * Creates a new UsagePerGroup RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UsagePerGroup RecordBuilder
   */
  public static iot.UsagePerGroup.Builder newBuilder(iot.UsagePerGroup.Builder other) {
    return new iot.UsagePerGroup.Builder(other);
  }

  /**
   * Creates a new UsagePerGroup RecordBuilder by copying an existing UsagePerGroup instance.
   * @param other The existing instance to copy.
   * @return A new UsagePerGroup RecordBuilder
   */
  public static iot.UsagePerGroup.Builder newBuilder(iot.UsagePerGroup other) {
    return new iot.UsagePerGroup.Builder(other);
  }

  /**
   * RecordBuilder for UsagePerGroup instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UsagePerGroup>
    implements org.apache.avro.data.RecordBuilder<UsagePerGroup> {

    private java.lang.String CoffeeMachineIdGroupIdKey;
    private java.lang.String CoffeeMachineId;
    private java.lang.String GroupId;
    private long count;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(iot.UsagePerGroup.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CoffeeMachineIdGroupIdKey)) {
        this.CoffeeMachineIdGroupIdKey = data().deepCopy(fields()[0].schema(), other.CoffeeMachineIdGroupIdKey);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CoffeeMachineId)) {
        this.CoffeeMachineId = data().deepCopy(fields()[1].schema(), other.CoffeeMachineId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.GroupId)) {
        this.GroupId = data().deepCopy(fields()[2].schema(), other.GroupId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.count)) {
        this.count = data().deepCopy(fields()[3].schema(), other.count);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing UsagePerGroup instance
     * @param other The existing instance to copy.
     */
    private Builder(iot.UsagePerGroup other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.CoffeeMachineIdGroupIdKey)) {
        this.CoffeeMachineIdGroupIdKey = data().deepCopy(fields()[0].schema(), other.CoffeeMachineIdGroupIdKey);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.CoffeeMachineId)) {
        this.CoffeeMachineId = data().deepCopy(fields()[1].schema(), other.CoffeeMachineId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.GroupId)) {
        this.GroupId = data().deepCopy(fields()[2].schema(), other.GroupId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.count)) {
        this.count = data().deepCopy(fields()[3].schema(), other.count);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'CoffeeMachineIdGroupIdKey' field.
      * @return The value.
      */
    public java.lang.String getCoffeeMachineIdGroupIdKey() {
      return CoffeeMachineIdGroupIdKey;
    }

    /**
      * Sets the value of the 'CoffeeMachineIdGroupIdKey' field.
      * @param value The value of 'CoffeeMachineIdGroupIdKey'.
      * @return This builder.
      */
    public iot.UsagePerGroup.Builder setCoffeeMachineIdGroupIdKey(java.lang.String value) {
      validate(fields()[0], value);
      this.CoffeeMachineIdGroupIdKey = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'CoffeeMachineIdGroupIdKey' field has been set.
      * @return True if the 'CoffeeMachineIdGroupIdKey' field has been set, false otherwise.
      */
    public boolean hasCoffeeMachineIdGroupIdKey() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'CoffeeMachineIdGroupIdKey' field.
      * @return This builder.
      */
    public iot.UsagePerGroup.Builder clearCoffeeMachineIdGroupIdKey() {
      CoffeeMachineIdGroupIdKey = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'CoffeeMachineId' field.
      * @return The value.
      */
    public java.lang.String getCoffeeMachineId() {
      return CoffeeMachineId;
    }

    /**
      * Sets the value of the 'CoffeeMachineId' field.
      * @param value The value of 'CoffeeMachineId'.
      * @return This builder.
      */
    public iot.UsagePerGroup.Builder setCoffeeMachineId(java.lang.String value) {
      validate(fields()[1], value);
      this.CoffeeMachineId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'CoffeeMachineId' field has been set.
      * @return True if the 'CoffeeMachineId' field has been set, false otherwise.
      */
    public boolean hasCoffeeMachineId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'CoffeeMachineId' field.
      * @return This builder.
      */
    public iot.UsagePerGroup.Builder clearCoffeeMachineId() {
      CoffeeMachineId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'GroupId' field.
      * @return The value.
      */
    public java.lang.String getGroupId() {
      return GroupId;
    }

    /**
      * Sets the value of the 'GroupId' field.
      * @param value The value of 'GroupId'.
      * @return This builder.
      */
    public iot.UsagePerGroup.Builder setGroupId(java.lang.String value) {
      validate(fields()[2], value);
      this.GroupId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'GroupId' field has been set.
      * @return True if the 'GroupId' field has been set, false otherwise.
      */
    public boolean hasGroupId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'GroupId' field.
      * @return This builder.
      */
    public iot.UsagePerGroup.Builder clearGroupId() {
      GroupId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'count' field.
      * @return The value.
      */
    public java.lang.Long getCount() {
      return count;
    }

    /**
      * Sets the value of the 'count' field.
      * @param value The value of 'count'.
      * @return This builder.
      */
    public iot.UsagePerGroup.Builder setCount(long value) {
      validate(fields()[3], value);
      this.count = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'count' field has been set.
      * @return True if the 'count' field has been set, false otherwise.
      */
    public boolean hasCount() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'count' field.
      * @return This builder.
      */
    public iot.UsagePerGroup.Builder clearCount() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UsagePerGroup build() {
      try {
        UsagePerGroup record = new UsagePerGroup();
        record.CoffeeMachineIdGroupIdKey = fieldSetFlags()[0] ? this.CoffeeMachineIdGroupIdKey : (java.lang.String) defaultValue(fields()[0]);
        record.CoffeeMachineId = fieldSetFlags()[1] ? this.CoffeeMachineId : (java.lang.String) defaultValue(fields()[1]);
        record.GroupId = fieldSetFlags()[2] ? this.GroupId : (java.lang.String) defaultValue(fields()[2]);
        record.count = fieldSetFlags()[3] ? this.count : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UsagePerGroup>
    WRITER$ = (org.apache.avro.io.DatumWriter<UsagePerGroup>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UsagePerGroup>
    READER$ = (org.apache.avro.io.DatumReader<UsagePerGroup>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
